# Generated by Django 5.1.4 on 2024-12-17 08:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Darbas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pavadinimas",
                    models.CharField(max_length=250, verbose_name="Pavadinimas"),
                ),
                (
                    "pastabos",
                    models.TextField(max_length=1000, verbose_name="Pastabos"),
                ),
            ],
            options={
                "verbose_name": "Darbas",
                "verbose_name_plural": "Darbai",
            },
        ),
        migrations.CreateModel(
            name="Darbuotojas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vardas", models.CharField(max_length=100, verbose_name="Vardas")),
                ("pavarde", models.CharField(max_length=100, verbose_name="Pavardė")),
                ("pareigos", models.CharField(max_length=250, verbose_name="Pareigos")),
            ],
            options={
                "verbose_name": "Darbuotojas",
                "verbose_name_plural": "Darbuotojai",
            },
        ),
        migrations.CreateModel(
            name="Klientas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vardas", models.CharField(max_length=100, verbose_name="Vardas")),
                ("pavarde", models.CharField(max_length=100, verbose_name="Pavardė")),
                ("imone", models.CharField(max_length=250, verbose_name="Įmonė")),
                (
                    "kontaktai",
                    models.CharField(max_length=250, verbose_name="Kontaktai"),
                ),
            ],
            options={
                "verbose_name": "Klientas",
                "verbose_name_plural": "Klientai",
            },
        ),
        migrations.CreateModel(
            name="Saskaita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "israsymo_data",
                    models.DateField(
                        blank=True, null=True, verbose_name="Išrašymo data"
                    ),
                ),
                (
                    "suma",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Suma"
                    ),
                ),
            ],
            options={
                "verbose_name": "Saskaita",
                "verbose_name_plural": "Saskaitos",
            },
        ),
        migrations.CreateModel(
            name="Projektas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pavadinimas",
                    models.CharField(max_length=250, verbose_name="Pavadinimas"),
                ),
                (
                    "pradzios_data",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Pradžios data"
                    ),
                ),
                (
                    "pabaigos_data",
                    models.DateField(
                        blank=True, null=True, verbose_name="Pabaigos data"
                    ),
                ),
                (
                    "darbai",
                    models.ManyToManyField(
                        to="projektuvaldymas.darbas", verbose_name="Darbai"
                    ),
                ),
                (
                    "darbuotojai",
                    models.ManyToManyField(
                        to="projektuvaldymas.darbuotojas", verbose_name="Darbuotojai"
                    ),
                ),
                (
                    "klientas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projektuvaldymas.klientas",
                    ),
                ),
                (
                    "vadovas",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saskaitos",
                    models.ManyToManyField(
                        to="projektuvaldymas.saskaita", verbose_name="Sąskaitos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projektas",
                "verbose_name_plural": "Projektai",
            },
        ),
    ]
