# Generated by Django 5.1.4 on 2024-12-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektuvaldymas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klientas",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
