# Generated by Django 5.1.4 on 2024-12-18 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektuvaldymas", "0002_alter_klientas_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="darbuotojas",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="projektas",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
