# Generated by Django 5.1.4 on 2024-12-19 14:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projektuvaldymas", "0006_projektas_aprasymas_projektas_nuotrauka_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projektas",
            name="aprasymas",
            field=tinymce.models.HTMLField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
